### ISSUE TITLE
 how  to  get  the  ground-truth  priors

### ISSUE THREAD

**Issue by myw8** [tyshiwo/FSRNet#3]
Hi,I can't understand  how  to  get  the  ground-truth  priors？  are they  images, How can I generate  them?

**Comment by tyshiwo** [comment]
Hi, 

Helen provides the gt of both parsing and landmarks. CelebA only provides the landmarks, so we use a state-of-the-art parsing method GFC (cvpr'17) to get the parsing maps.

**Comment by hao-qiang** [comment]
Hi,
I cannot find parsing maps from Helen Dataset webset (http://www.ifp.illinois.edu/~vuongle2/helen/), can I find them in other place? 
Thx

**Comment by JauB1981** [comment]
Hi tyshiwo
From where can we download the gt of  parsing abd landmarks of Helen dataset please ?

**Comment by hao-qiang** [comment]
you can try celeba-mask dataset. Qiang Hao 邮箱：haoqiang1209@gmail.com 签名由 网易邮箱大师 定制 On 08/12/2019 04:13, JauB1981 wrote: Hi tyshiwo From where can we download the gt of parsing abd landmarks of Helen dataset please ? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hao-qiang** [comment]
> Hi tyshiwo
> From where can we download the gt of parsing abd landmarks of Helen dataset please ?

Please check this repo:
https://github.com/switchablenorms/CelebAMask-HQ

**Comment by JauB1981** [comment]
@hao-qiang the repo doesn't containing the gt of parsing and landmarks ! Do we have to execute some programs from this repo to get the data as requested or how to do to get the desired data ?

**Comment by hao-qiang** [comment]
@JauB1981 CelebAMask-HQ is a face parsing dataset, so you can get parsing gt there.

**Comment by JauB1981** [comment]
@hao-qiang please do you have andy idea from where we can download gt in .npy format ?

**Comment by ComingPeopleHW** [comment]
> Hi tyshiwo
> From where can we download the gt of parsing abd landmarks of Helen dataset please ?
HI, Have you find where can download parsing map of Helen dataset?

**Comment by ComingPeopleHW** [comment]
Who look Helen Dataset parsing map GT could check this work : http://pages.cs.wisc.edu/~lizhang/projects/face-parsing/
