### ISSUE TITLE
The problem of the Model

### ISSUE THREAD

**Issue by zxyjfj** [tyshiwo/FSRNet#4]
Dear Mr. Tai:

       I am a graduate student of Anhui University of Technology in China. Recently, I read one of your articles, titled FSRNet: End-to-End Learning Face Super-Resolution with Facial Priors in CVPR2018. But when I run the FSRNet Code which you have provided on the GitHub, I found that its performance is not good: the super-resolved images have a lot of noise. Will it be that you have changed the model and did not update it to GitHub?  Could you send me a copy of you model? Thanks a lot! My Email is zhengxiaoyu51888@163.com.By the way, I also want to know how to get the ground-truth images from the CelebA and Helen dataset?

       Thank you for you kind consideration of this request.

       Sincerely: Zhengxiaoyu

 

The images with a lot of noise
![output_2_18305](https://user-images.githubusercontent.com/31607618/43621369-a1abba68-9709-11e8-95d3-010b1d8260e8.jpg)
![output_2_18433](https://user-images.githubusercontent.com/31607618/43621370-a1d9acca-9709-11e8-8089-e270e3cd01da.jpg)
![output_2_18617](https://user-images.githubusercontent.com/31607618/43621371-a2066d14-9709-11e8-802c-a1ffbe17fe30.jpg)

**Comment by tyshiwo** [comment]
Hi,

1. We downsampled the images in torch not in python or matlab, this may cause the difference. 

2. Helen provides the gt of parsing and landmarks. For celebA, we use GFC (cvpr'17) to get the parsing maps.

**Comment by zxyjfj** [comment]
Hi,
     These images are all provided by you. These images can be found in the folder FSRNet/data/helen_val_50_LR_8x/. So, I think This problem cannot be caused by the difference of the images.

**Comment by zxyjfj** [comment]
Hi, 
These images are all provided by you. These images can be found in the folder FSRNet/data/helen_val_50_LR_8x/. So, I think This problem cannot be caused by the difference of the images.
