### ISSUE TITLE
where does the number "197" come from in provided torch model

### ISSUE THREAD

**Issue by pangwong** [tyshiwo/FSRNet#6]
Hi, 
I find there is a conv layer with output size 197 in your provided model Helen_8x_cpu.t7.
```
th> model.modules[50]
nn.SpatialConvolution(128 -> 197, 1x1)                                                                      [0.0001s]	
```

As you paper states, here should be a 1x1 conv mapping hourglass feature map to generate the landmark heatmaps and the parsing maps.

Howerer, the number of ground truth landmarks is 194 and the number of parsing maps is 11. I don't understand where the "197" comes from.

Thanks for your reply.

**Comment by tyshiwo** [comment]
Hi, 

197 indicates 194 estimated heatmaps for alignment and 3 estimated global parsing maps.
