### ISSUE TITLE
Which Images do you use for CelebA Training?

### ISSUE THREAD

**Issue by uyekt** [tyshiwo/FSRNet#9]
Hi there,

Thanks for this repo!

A question though: In your paper you write "For celebA dataset, we use the first 18,000 images for training, and the following 100 images for evaluation."

However, in this repo you have 1000images for CelebA and those are the last 1000 of the dataset.

So do you use the image 000001.jpg up to 018000.jpg for training and the 018000.jpg to 018100.jpg for evaluation like you say in the paper or is it maybe a typo?

It would be nice if you could clear this up for reproducibility :-) 

Thanks in advance for your help!

**Comment by tyshiwo** [comment]
Hi,

The results reported in the paper is coming from the model trained by the first 18,000 images in CelebA, and tested by the following 100 images (i.e., 18001 ~ 18100).

**Comment by jotoy** [comment]
> Hi,
> 
> The results reported in the paper is coming from the model trained by the first 18,000 images in CelebA, and tested by the following 100 images (i.e., 18001 ~ 18100).

So, can you upload the testing images reported in your paper(i.e., 18001 ~ 18100)? BTW, which images do you use for testing Helen DATASET?
